version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: db
    hostname: db
    ports:
      - '3306:3306'
    networks:
      - backend


networks:
  backend:
    driver: 'bridge'